### ISSUE TITLE
Response "200 no error": string: {"status_code":210,"status_message":"Application not found","response":null}

### ISSUE THREAD

**Issue by BeRMaNyA** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#87] opened 2015-04-09 04:11 UTC
Hi, I just started implementing this plugin in order to manage the push notifications from my app. I'm currently using IonicFramework beta-13 and Cordova 3.5.0-0.2.7 and when I run my app I'm getting the error that I mentioned in the title:

Response "200 no error": string: {"status_code":210,"status_message":"Application not found","response":null}

Let me show you my code:

```coffeescript
initPushwoosh = ->
  pushNotification = window.plugins.pushNotification
  #set push notification callback before we initialize the plugin
  document.addEventListener 'push-notification', (event) ->
    #get the notification payload
    notification = event.notification
    #display alert to the user for example
    alert notification.aps.alert
    #clear the app badge
    pushNotification.setApplicationIconBadgeNumber 0
    return
  #initialize the plugin
  pushNotification.onDeviceReady pw_appid: '46BDA-08935'
  #register for pushes
  pushNotification.registerDevice ((status) ->
    deviceToken = status['deviceToken']
    console.warn 'registerDevice: ' + deviceToken
    return
  ), (status) ->
    console.warn 'failed to register : ' + JSON.stringify(status)
    alert JSON.stringify([
      'failed to register '
      status
    ])
    return
  #reset badges on app start
  pushNotification.setApplicationIconBadgeNumber 0
  return

Teamitup.run ($ionicPlatform, $rootScope, $cordovaPush, $cordovaDialogs, $cordovaMedia) ->
  document.addEventListener 'deviceready', ->
    initPushwoosh()
```

I appreciate your help.

**Comment by BeRMaNyA** [comment] 2015-04-09 04:12
It seems the library send this request:

2015-04-09 01:01:30.462 Teamitup[261:21304] Sending request: {"request":{"hwid":"6DAB498E-E4A0-43C1-8120-1413E91040BE","application":"","v":"2.5"}}
2015-04-09 01:01:30.463 Teamitup[261:21304] To urL https://cp.pushwoosh.com/json/1.3/applicationOpen

"application":""

mmmm

**Comment by shaders** [comment] 2015-04-09 06:21
Which plugin version do you use? Somehow the SDK does not see pw_appid parameter from onDeviceReady (have no idea why yet).

Do you see this line in the console log?
PushNotification.registerDevice: Missing Pushwoosh App ID

Try to add "Pushwoosh_APPID" key to Info.plist with the Pushwoosh App Id value - will it work?

**Comment by xifengzhu** [comment] 2015-05-20 13:27
I also got the same problem with using ionic and pushwoosh.
my xcode log:
```
Sending request: {"request":{"application":"","v":"2.5","hwid":"3BD78B26-18D1-4390-85A2-4DCDBC49E69C"}}

To urL https://cp.pushwoosh.com/json/1.3/applicationOpen

location services authorization status has not been determined yet

Response "200 no error": string: {"status_code":210,"status_message":"Application not found","response":null}

sending appOpen failed
```

I appreciate your help.

**Comment by shaders** [comment] 2015-05-20 13:30
Is this iOS or Android?
For iOS try to add "Pushwoosh_APPID" key to Info.plist with the Pushwoosh App Id value - will it work?

**Comment by xifengzhu** [comment] 2015-05-20 13:43
Is IOS, when I add the Pushwoosh_APPID, but I get another error message: 
```
 Response "200 no error": string: {"status_code":200,"status_message":"OK","response":null}
```

**Comment by shaders** [comment] 2015-05-20 13:51
This is not an error message. This is success message.

**Comment by xifengzhu** [comment] 2015-05-20 14:01
Thank for you help.But when  I start my app  I got a blank page.

**Comment by shaders** [comment] 2015-05-20 14:07
Please note Pushwoosh does not display any pages. Closing thread.

**Closed by shaders** 2015-05-20 14:07 UTC

**Comment by castillobg** [comment] 2015-07-04 14:33
Hi. Sorry to reopen this. The info.plist workaround worked, nevertheless, I understand this shouldn't be the way to do it. @shaders What do you recommend I do to avoid having to add the key-value pair to my info.plist file?

**Comment by shaders** [comment] 2015-07-06 11:52
The key-value pair is official way in Native SDK. If you send basic ionic sample that reproduces this behavior it would be great.

**Comment by castillobg** [comment] 2015-07-06 14:48
Sure! Here it is. I omitted some code for simplicity's sake.

#### app.js

    $ionicPlatform.ready(function () {
        ...
        pushService.initPush();
        ...
    });

#### push-service.js
    
    ...
    function initPush () {
        if (device.platform == 'Android') {
            registerPushwooshAndroid();
        }
        else if(device.platform == 'iPhone' || device.platform == 'iOS') {
            registerPushwooshIOS();
        }
    };
    ...
    function registerPushwooshIOS() {
        var pushNotification = window.plugins.pushNotification;

        //set push notification callback before we initialize the plugin
        document.addEventListener('push-notification',
            function(event) {
                // Handle the notification.
            }
        );

        //initialize the plugin
        pushNotification.onDeviceReady({pw_appid : 'XXXXX-XXXXX' });

        //register for pushes
        pushNotification.registerDevice(
            function(status) {
                // Handle success.
            },
            function(status) {
                // Handle failure.
            }
        );

        //reset badges on app start
        pushNotification.setApplicationIconBadgeNumber(0);
    }
    ...

**Comment by shaders** [comment] 2015-07-06 15:24
No, I need full ionic project to compile and run. The same code runs perfectly in the sample project on Cordova.

**Comment by castillobg** [comment] 2015-07-06 15:26
Oh. I'm sorry, I can't do that. I guess I'll reinstall the plugin again then! Thanks for your help :)

**Comment by shaders** [comment] 2015-07-07 14:57
Have you tried this sample (not official): https://github.com/TiagoSilvaPereira/ionic-pushwoosh

**Comment by castillobg** [comment] 2015-07-07 15:00
Hi! Thanks for the suggestion @shaders but that example is only for Android. The issue I'm having is for iOS only.

**Comment by Wang0620** [comment] 2015-08-13 02:41
I am also getting the same issue on iOS. Here is error log:
Response "200 no error": string: {"status_code":210,"status_message":"Application not found","response":null}

Please help and update me. Thanks

**Comment by shaders** [comment] 2015-08-13 08:00
Do you have a sample I can try?

**Comment by Wang0620** [comment] 2015-08-14 03:19
I was getting that error in the log console. But for now the push notification works although the error is shown in the console. I think that error can be ignored. 
Thanks taking care of my issue, Shaders. :+1:

**Comment by chornbe** [comment] 2016-08-22 22:26
Shaders, if I understand this thread correctly, adding the parameters to the onDeviceReady(...) call isn't working...? What's the point of that call, then? I'm getting the same error, then when RegisterDevice(...) is called the app usually just locks up and requires a forceful shut down. I'm using the latest version of the plugin building an iOS app via Trigger.IO. 

I have had ZERO success getting this working and am ready to just cancel my PushWoosh subscription.

**Comment by shaders** [comment] 2016-08-23 14:13
Why do you post and use Phonegap Plugin when you are working with Trigger.IO? That's completely different platforms!

The document is available here:
http://docs.pushwoosh.com/docs/triggerio

Make sure you are using the latest module and also try the Ready-To-Work-Out-Of-The-Box sample:
https://github.com/Pushwoosh/pushwoosh-trigger-io/tree/master/Sample

**Comment by chornbe** [comment] 2016-08-23 14:18
Because the issue isn't with phone gap or trigger; it's in the pushwoosh
system or config. I'm making this fairly well considered assumption based
on the diversity of developers and platforms exhibiting the exact same
error number and message, and symptoms. I've been researching workarounds
and fixes for this for weeks now, with absolutely zero success and I
thought if I posted outside the narrow focus of trigger, I'd get more
information. Instead, I generally see you telling people they've configured
it incorrectly and closing threads without verified resolution.

It's frustrating to us, the users who want to use your system and are
paying to do so, without any viable push notifications ever being sent
beyond the test stuff.

:(






Chris Hornberger
chris.hornberger@gmail.com

**Comment by shaders** [comment] 2016-08-23 14:30
I don't understand. This thread is related to Phonegap and was closed due to successful case resolution:
Thanks taking care of my issue, Shaders. 👍

This is not the time to resurrect the post from 2015. If you have issues - please open separate ticket with the detailed problem description.

**Comment by domonock** [comment] 2018-11-02 15:42
| Status:   "200 no error"
| Response: {"status_code":210,"status_message":"Application not found","response":null}

iOS application 

I add "Pushwoosh_APPID" key to Info.plist

> Is this iOS or Android?
> For iOS try to add "Pushwoosh_APPID" key to Info.plist with the Pushwoosh App Id value - will it work?
