### ISSUE TITLE
Possible iOS 9 issue - one push alerts twice

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-3.0-plugin#125] opened 2015-09-18 13:09 UTC
When sending a single push to an iOS 9 app, the iPhone (6) alerts two times. Note that the badge is correct and also the number of shown notifications is also correct once you look in the notifications tab at the end.
It does not happen on iOS 8. Also, no problem on Android.

The app is question is built in an XCode 7 environment using iOS 9 SDK. This was tested against sandboxed/development gateway(s). pushwoosh-cordova-plugin ver. 3.6.5-1.

Here's a video recording:
https://youtu.be/cab02jKZXk0

**Comment by shaders** [comment] 2015-09-18 14:21
Could you provide logs from the console of the app on iOS9?  That's super weird. Do you use release version of iOS9 (not beta)?

**Comment by zarko-tg** [comment] 2015-09-21 08:08
Yep, I used the official iOS9.
Please provide your email address since the log contains a bit of sensitive information.

**Comment by shaders** [comment] 2015-09-21 11:25
Could you please send the logs to Pushwoosh suppport, please mention this thread on github.

**Comment by zarko-tg** [comment] 2015-09-21 11:36
@shaders done. Find email with subject "pushwoosh-phonegap-3.0-plugin, GitHub issue 125" / request 10710.

**Comment by zarko-tg** [comment] 2015-09-21 12:05
I just also confirmed the same issue for app using Production (aka Distribution) gateway.

**Comment by shaders** [comment] 2015-09-21 13:02
Did you change Provisioning Profile / Developer Certificate on that app? I can see your device in the Database with different push token that the one in the logs file. However push token change is fine and handled correctly on Pushwoosh side.

But if HWID was changed - this could be a problem. In this case device will be subscribed twice (with two different HWID's). That's why you could receive two pushes instead of one.

**Comment by zarko-tg** [comment] 2015-09-21 13:11
It's a iPhone 6 i use for development and it has taken iOS updates from 8.x to 9.0 betas and now has the official 9.0 on it. Surely I haven't done anything directly to change HWID. Is that even possible?

And yes, I normally develop and test with two different editions of the app. One is built and signed for development and testing and is configured to talk the Pushwoosh sandbox "application". The other one is built and signed for production and release in app store, configured to to talk to the Pushwoosh production "application" / gateway.

At last, I'd say this issue is not too important unless it can or has happened to others. And as a reminder that an iPhone 5 sitting next to me with iOS 8 on it does not manifest the problem.

**Comment by shaders** [comment] 2015-09-21 13:14
I would recommend to unregister device from push notifications (by calling unregisterDevice method). Then try to send push notification to check if it will arrive (that will confirm duplicate HWID theory)?

**Comment by zarko-tg** [comment] 2015-09-21 13:20
Yes, that's interesting but it won'† lead anywhere since it's an app that has own user login and logout functionality. PW registration is done upon login and un-registration on logout.
I'll try to find a little time soon to reproduce using a new test app based on https://github.com/Pushwoosh/phonegap-3-sample-app or something.

**Comment by tysjiang** [comment] 2015-09-21 17:22
hmm.... I think I'm seeing the same issue with iOS9 on a iPhone 6 app.  After registering the app to pushwoosh, notifications are alerted twice.  
Strange thing is, from looking at my server logs and pushwoosh history, my server only sent out 1 notification and pushwoosh's history shows likewise, only one notification, yet on the device itself, the alert goes off twice.

**Comment by shaders** [comment] 2015-09-22 09:02
Got the same reproduced here. Looks like iOS9 bug :(
What is interesting that if Alert Style is set to "Alerts" - only one alert is displayed.
It's only "Banners" that trigger alert twice.
If you go to the lock screen - only one alert is displayed as well. If you are in the app - the push received only once.
So you can see two alerts only when display mode is set to "Banners" (which is default one) and you are on the home screen.

Tested on iPhone 6 plus, iOS 9.

**Comment by MrPro100** [comment] 2015-09-30 10:30
+1 Same problem

**Comment by mjtognetti** [comment] 2015-10-09 18:55
We're seeing the same issue - one notification in our logs, pushwoosh logs, and the notification tray, but two alerts. Has anyone found any leads on this?

**Comment by RustyGumbo** [comment] 2015-10-21 18:37
Maybe a bit unrelated but I'm running into the exact same issue using the phonegap-plugin-push plugin (once when locked, once in-app, twice at home screen)

**Comment by 258076067** [comment] 2015-10-22 11:49
I'm having same issue with local notification,  anyone figured this our yet ?

**Comment by shaders** [comment] 2015-10-22 13:31
Found the reason for this. It's a bug of iOS 9.X (still happening in the latest version), but I think it's possible to workaround.

**Comment by shaders** [comment] 2015-10-30 20:35
And fixed in https://github.com/Pushwoosh/pushwoosh-phonegap-3.0-plugin/commit/db0a73431e99d97e3ffbd7ca9858a5f64a8f195c

**Closed by shaders** 2015-10-30 20:35 UTC

**Comment by mirono** [comment] 2015-11-03 17:11
Can you specify what the workaround is? We are having the same issue with our native app on iOS9 and iPhone 6.

**Comment by shaders** [comment] 2015-11-03 17:16
Just update to the latest version of the plugin.

**Comment by mirono** [comment] 2015-11-03 19:11
Thanks shaders, but maybe I wasn't clear enough. We don't use the plugin, but we have the same issue in our iOS app, and we wanted to apply the same fix. This is why I'm asking what was the workaround.

**Comment by shaders** [comment] 2015-11-03 20:47
Why don't you use plugin? You can send push token to your server and use your system but still have all the features available by Pushwoosh!

**Comment by zhang826728** [comment] 2015-11-11 09:54
You use two kinds of push?

**Comment by zhang826728** [comment] 2015-11-11 09:55
I use two kinds of here, I do not know whether there is an inevitable link

**Comment by AppsCanFly** [comment] 2015-11-15 22:36
Just to re-ask mirono's question, but what workaround exactly did you guys do? I'm not using this plugin, and I was wondering if I could apply the same technique/workaround on what I'm working on. Thanx

**Comment by shaders** [comment] 2015-11-16 06:37
If you receive two alerts - update to the latest plugin version. This thread is closed now.

**Comment by vivekgajbe** [comment] 2016-06-27 10:59
I am also getting same issue When sending a single push to an iOS 9 app, the iPad mini alerts two times.(It is getting twice ,sound also getting twice  but it display once in notification bar)
